spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:1234}
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/spring}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  singerKey: ${JWT_ACCESS_TOKEN_SIGNERKEY:"JWT_ACCESS_TOKEN_SIGNERKEY=6ycsb5jxe6lplzxtz9e3jvl3btrpd5kh"}
  valid-duration: 120 # in second
  refreshable-duration: 520 # in second